sudo: false
language: python
matrix:
  include:
    - python: "3.5"
    - install:
      - pip install -r test_requirements.txt
      - pip install docker-compose --upgrade
      - git clone https://github.com/edx/devstack.git
      - cd devstack
      - make dev.clone
      - make dev.provision
      - cd ..
      script:
        - (make dev.up &); sleep 5;
        - tox -e py35 ./edx_api/integration_test.py
      env:
        - ACCESS_TOKEN=token
        - BASE_URL=http://localhost:18000/
      services:
        - docker
