sudo: false
language: python:3.5
matrix:
  include:
    - install:
      - pip install -r test_requirements.txt
      - pip install docker-compose --upgrade
      - git clone https://github.com/edx/devstack.git
      - cd devstack
      - make dev.clone
      - docker-compose up -d mysql mongo
      - sleep 10
      - docker exec -i edx.devstack.mysql mysql -uroot mysql < provision.sql
      - docker exec -i edx.devstack.mongo mongo < mongo-provision.js
      - bash ./provision-lms.sh
      - cat ../provision-devstack.sh | docker exec -i edx.devstack.lms bash -i
      - cd ..
      script:
        - make dev.up
        - sleep 60 # Wait for LMS to start
        - tox -e py35 ./edx_api/integration_test.py
      env:
        - ACCESS_TOKEN=token
        - BASE_URL=http://localhost:18000/
      services:
        - docker
